-- =====================================================================
-- QLVB - PostgreSQL - PHIEN BAN HOAN CHINH
--
-- Noi dung:
--   1. Quan ly van ban den, van ban di va ho so.
--   2. Them van ban vao ho so, luu nguoi them va thoi gian them.
--   3. Chuan hoa vi tri luu tru thanh cac bang danh muc:
--      toa_nha -> phong_luu_tru -> ke_tu_luu_tru
--      -> ngan_luu_tru -> hop_luu_tru.
--   4. Phan quyen RBAC.
--   5. Quan ly quyet dinh.
--   6. Moi quyet dinh co the co nhieu thanh phan lien quan:
--      ho ten, don vi, chuc vu va vai tro.
--
-- LUU Y:
--   File nay xoa va tao lai schema public.
--   Chi chay khi database khong co du lieu quan trong.
-- =====================================================================

BEGIN;

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO public;

SET search_path TO public;

-- =====================================================================
-- I. DANH MUC VA TO CHUC
-- =====================================================================

CREATE TABLE danh_muc_loai_vb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_loai_vb     varchar(100) NOT NULL UNIQUE,
    mo_ta           text
);

CREATE TABLE co_quan_to_chuc (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_co_quan     varchar(255) NOT NULL,
    organ_id        varchar(13) NOT NULL UNIQUE,
    dia_chi         varchar(500)
);

CREATE TABLE can_bo (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten          varchar(100) NOT NULL,
    chuc_vu         varchar(100),
    co_quan_id      integer NOT NULL,

    CONSTRAINT fk_can_bo_co_quan
        FOREIGN KEY (co_quan_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- =====================================================================
-- II. PHAN QUYEN RBAC
-- Tao tai_khoan truoc cac bang van ban de co the luu nguoi them van ban
-- vao ho so.
-- =====================================================================

CREATE TABLE tai_khoan (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id           integer UNIQUE,
    ten_dang_nhap       varchar(100) NOT NULL UNIQUE,
    mat_khau_hash       varchar(255) NOT NULL,
    trang_thai          varchar(20) NOT NULL DEFAULT 'ACTIVE',
    ngay_tao            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat       timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tai_khoan_can_bo
        FOREIGN KEY (can_bo_id)
        REFERENCES can_bo(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_tai_khoan_trang_thai
        CHECK (trang_thai IN ('ACTIVE', 'LOCKED', 'INACTIVE'))
);

CREATE TABLE vai_tro (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_vai_tro      varchar(50) NOT NULL UNIQUE,
    ten_vai_tro     varchar(100) NOT NULL,
    mo_ta           varchar(500)
);

CREATE TABLE quyen (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_quyen        varchar(100) NOT NULL UNIQUE,
    ten_quyen       varchar(150) NOT NULL,
    module          varchar(50) NOT NULL,
    hanh_dong       varchar(30) NOT NULL
);

CREATE TABLE tai_khoan_vai_tro (
    tai_khoan_id    integer NOT NULL,
    vai_tro_id      integer NOT NULL,

    PRIMARY KEY (tai_khoan_id, vai_tro_id),

    CONSTRAINT fk_tkvt_tai_khoan
        FOREIGN KEY (tai_khoan_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_tkvt_vai_tro
        FOREIGN KEY (vai_tro_id)
        REFERENCES vai_tro(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE vai_tro_quyen (
    vai_tro_id      integer NOT NULL,
    quyen_id        integer NOT NULL,

    PRIMARY KEY (vai_tro_id, quyen_id),

    CONSTRAINT fk_vtq_vai_tro
        FOREIGN KEY (vai_tro_id)
        REFERENCES vai_tro(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_vtq_quyen
        FOREIGN KEY (quyen_id)
        REFERENCES quyen(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- =====================================================================
-- III. VI TRI LUU TRU DUOC CHUAN HOA
-- Nguoi dung chon theo thu tu:
-- toa nha -> phong -> ke/tu -> ngan -> hop.
-- Khong con nhap chuoi tu do tren bang ho_so.
-- =====================================================================

CREATE TABLE toa_nha (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_toa_nha      varchar(50) NOT NULL UNIQUE,
    ten_toa_nha     varchar(255) NOT NULL,
    dia_chi         varchar(500),
    trang_thai      varchar(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT chk_toa_nha_trang_thai
        CHECK (trang_thai IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE phong_luu_tru (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toa_nha_id      integer NOT NULL,
    ma_phong        varchar(50) NOT NULL,
    ten_phong       varchar(100) NOT NULL,
    ghi_chu         text,
    trang_thai      varchar(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT fk_phong_toa_nha
        FOREIGN KEY (toa_nha_id)
        REFERENCES toa_nha(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_phong_toa_nha
        UNIQUE (toa_nha_id, ma_phong),

    CONSTRAINT chk_phong_trang_thai
        CHECK (trang_thai IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE ke_tu_luu_tru (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phong_id        integer NOT NULL,
    ma_ke_tu        varchar(50) NOT NULL,
    ten_ke_tu       varchar(100) NOT NULL,
    ghi_chu         text,
    trang_thai      varchar(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT fk_ke_tu_phong
        FOREIGN KEY (phong_id)
        REFERENCES phong_luu_tru(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_ke_tu_phong
        UNIQUE (phong_id, ma_ke_tu),

    CONSTRAINT chk_ke_tu_trang_thai
        CHECK (trang_thai IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE ngan_luu_tru (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ke_tu_id        integer NOT NULL,
    ma_ngan         varchar(50) NOT NULL,
    ten_ngan        varchar(100),
    ghi_chu         text,
    trang_thai      varchar(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT fk_ngan_ke_tu
        FOREIGN KEY (ke_tu_id)
        REFERENCES ke_tu_luu_tru(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_ngan_ke_tu
        UNIQUE (ke_tu_id, ma_ngan),

    CONSTRAINT chk_ngan_trang_thai
        CHECK (trang_thai IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hop_luu_tru (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ngan_id         integer NOT NULL,
    ma_hop          varchar(50) NOT NULL,
    ten_hop         varchar(100),
    ghi_chu         text,
    trang_thai      varchar(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT fk_hop_ngan
        FOREIGN KEY (ngan_id)
        REFERENCES ngan_luu_tru(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_hop_ngan
        UNIQUE (ngan_id, ma_hop),

    CONSTRAINT chk_hop_trang_thai
        CHECK (trang_thai IN ('ACTIVE', 'INACTIVE'))
);

-- =====================================================================
-- IV. HO SO VA VAN BAN
-- =====================================================================

CREATE TABLE ho_so (
    ma_ho_so            varchar(50) PRIMARY KEY,
    tieu_de_ho_so       varchar(500) NOT NULL,
    thoi_han_bao_quan   varchar(50),
    che_do_su_dung      varchar(50),
    ngay_bat_dau        date,
    ngay_ket_thuc       date,
    so_luong_trang      integer NOT NULL DEFAULT 0,
    so_luong_van_ban    integer NOT NULL DEFAULT 0,
    nguoi_lap           varchar(100),
    ngon_ngu            varchar(50),
    ghi_chu             text,

    -- Thong tin nghiep vu bo sung
    file_catalog        integer,
    file_notation       varchar(50),
    trang_thai          varchar(50) NOT NULL DEFAULT 'DANG_MO',

    -- Ho so duoc dat trong mot hop luu tru
    hop_luu_tru_id      integer,

    CONSTRAINT fk_ho_so_hop_luu_tru
        FOREIGN KEY (hop_luu_tru_id)
        REFERENCES hop_luu_tru(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_ho_so_ngay
        CHECK (
            ngay_ket_thuc IS NULL
            OR ngay_bat_dau IS NULL
            OR ngay_ket_thuc >= ngay_bat_dau
        ),

    CONSTRAINT chk_ho_so_so_luong_trang
        CHECK (so_luong_trang >= 0),

    CONSTRAINT chk_ho_so_so_luong_van_ban
        CHECK (so_luong_van_ban >= 0),

    CONSTRAINT chk_ho_so_trang_thai
        CHECK (trang_thai IN ('DANG_MO', 'DA_DONG', 'DA_LUU_TRU'))
);

CREATE TABLE van_ban_den (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_den                  integer NOT NULL,
    ky_hieu                 varchar(100),
    ngay_den                date NOT NULL,
    ngay_ban_hanh           date,
    co_quan_ban_hanh_id     integer,
    ma_loai_vb_id           integer NOT NULL,
    trich_yeu               text NOT NULL,
    ngon_ngu                varchar(30),
    so_trang                integer,
    ho_ten_nguoi_ky         varchar(100),
    chuc_vu_nguoi_ky        varchar(100),
    linh_vuc                text,
    do_khan                 integer,
    don_vi_nhan             text,
    han_giai_quyet          date,
    y_kien_chi_dao          text,

    -- Quan ly xu ly
    trang_thai_xu_ly        varchar(50) NOT NULL DEFAULT 'CHO_XU_LY',
    nguoi_xu_ly_id          integer,

    -- Them van ban vao ho so
    ma_ho_so                varchar(50),
    stt_trong_ho_so         integer,
    ngay_them_ho_so         timestamp without time zone,
    nguoi_them_ho_so_id     integer,

    CONSTRAINT fk_van_ban_den_co_quan
        FOREIGN KEY (co_quan_ban_hanh_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_van_ban_den_loai_vb
        FOREIGN KEY (ma_loai_vb_id)
        REFERENCES danh_muc_loai_vb(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_van_ban_den_ho_so
        FOREIGN KEY (ma_ho_so)
        REFERENCES ho_so(ma_ho_so)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_van_ban_den_nguoi_xu_ly
        FOREIGN KEY (nguoi_xu_ly_id)
        REFERENCES can_bo(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_van_ban_den_nguoi_them_ho_so
        FOREIGN KEY (nguoi_them_ho_so_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_van_ban_den_so_den
        CHECK (so_den > 0),

    CONSTRAINT chk_van_ban_den_so_trang
        CHECK (so_trang IS NULL OR so_trang >= 0),

    CONSTRAINT chk_van_ban_den_do_khan
        CHECK (do_khan IS NULL OR do_khan BETWEEN 1 AND 5),

    CONSTRAINT chk_van_ban_den_stt_ho_so
        CHECK (stt_trong_ho_so IS NULL OR stt_trong_ho_so > 0),

    CONSTRAINT chk_van_ban_den_trang_thai
        CHECK (
            trang_thai_xu_ly IN (
                'CHO_XU_LY',
                'DANG_XU_LY',
                'DA_XU_LY',
                'TU_CHOI'
            )
        ),

    CONSTRAINT chk_van_ban_den_thong_tin_ho_so
        CHECK (
            (ma_ho_so IS NULL
                AND stt_trong_ho_so IS NULL
                AND ngay_them_ho_so IS NULL
                AND nguoi_them_ho_so_id IS NULL)
            OR
            (ma_ho_so IS NOT NULL
                AND stt_trong_ho_so IS NOT NULL)
        )
);

CREATE TABLE van_ban_di (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_ky_hieu              varchar(50),
    ngay_ban_hanh           date,
    trich_yeu               text NOT NULL,
    don_vi_soan_thao_id     integer NOT NULL,
    ma_loai_vb_id           integer NOT NULL,
    ngon_ngu                varchar(30),
    so_trang                integer,
    ghi_chu                 text,
    nguoi_ky_id             integer,
    chuc_vu_nguoi_ky        varchar(100),
    noi_nhan                varchar(100),
    muc_do_khan             integer,
    han_tra_loi             date,

    -- Thong tin phat hanh
    so_luong_ban_phat_hanh  integer,
    trang_thai              varchar(50) NOT NULL DEFAULT 'DRAFT',

    -- Them van ban vao ho so
    ma_ho_so                varchar(50),
    stt_trong_ho_so         integer,
    ngay_them_ho_so         timestamp without time zone,
    nguoi_them_ho_so_id     integer,

    CONSTRAINT fk_van_ban_di_don_vi_soan_thao
        FOREIGN KEY (don_vi_soan_thao_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_van_ban_di_loai_vb
        FOREIGN KEY (ma_loai_vb_id)
        REFERENCES danh_muc_loai_vb(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_van_ban_di_nguoi_ky
        FOREIGN KEY (nguoi_ky_id)
        REFERENCES can_bo(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_van_ban_di_ho_so
        FOREIGN KEY (ma_ho_so)
        REFERENCES ho_so(ma_ho_so)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_van_ban_di_nguoi_them_ho_so
        FOREIGN KEY (nguoi_them_ho_so_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_van_ban_di_so_trang
        CHECK (so_trang IS NULL OR so_trang >= 0),

    CONSTRAINT chk_van_ban_di_muc_do_khan
        CHECK (muc_do_khan IS NULL OR muc_do_khan BETWEEN 1 AND 5),

    CONSTRAINT chk_van_ban_di_so_luong_phat_hanh
        CHECK (
            so_luong_ban_phat_hanh IS NULL
            OR so_luong_ban_phat_hanh >= 0
        ),

    CONSTRAINT chk_van_ban_di_stt_ho_so
        CHECK (stt_trong_ho_so IS NULL OR stt_trong_ho_so > 0),

    CONSTRAINT chk_van_ban_di_trang_thai
        CHECK (
            trang_thai IN (
                'DRAFT',
                'SUBMITTED',
                'APPROVED',
                'ISSUED',
                'REVOKED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_van_ban_di_thong_tin_ho_so
        CHECK (
            (ma_ho_so IS NULL
                AND stt_trong_ho_so IS NULL
                AND ngay_them_ho_so IS NULL
                AND nguoi_them_ho_so_id IS NULL)
            OR
            (ma_ho_so IS NOT NULL
                AND stt_trong_ho_so IS NOT NULL)
        )
);

CREATE TABLE noi_nhan_van_ban (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    van_ban_di_id           integer NOT NULL,
    co_quan_nhan_id         integer NOT NULL,
    phuong_thuc_gui         varchar(100),

    CONSTRAINT fk_noi_nhan_van_ban_di
        FOREIGN KEY (van_ban_di_id)
        REFERENCES van_ban_di(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_noi_nhan_co_quan
        FOREIGN KEY (co_quan_nhan_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_noi_nhan_van_ban
        UNIQUE (van_ban_di_id, co_quan_nhan_id)
);

-- Bang file_dinh_kem su dung quan he da hinh:
-- loai_van_ban = VAN_BAN_DEN thi van_ban_id tham chieu van_ban_den.id.
-- loai_van_ban = VAN_BAN_DI  thi van_ban_id tham chieu van_ban_di.id.
-- PostgreSQL khong the tao FOREIGN KEY truc tiep cho mot cot tham chieu
-- den hai bang, do do rang buoc nay duoc xu ly o tang nghiep vu.
CREATE TABLE file_dinh_kem (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loai_van_ban    varchar(20) NOT NULL,
    van_ban_id      integer NOT NULL,
    ten_file        varchar(255) NOT NULL,
    duong_dan       varchar(500) NOT NULL,
    dinh_dang       varchar(20),
    dung_luong      double precision,
    ngay_tao        timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_file_loai_van_ban
        CHECK (loai_van_ban IN ('VAN_BAN_DEN', 'VAN_BAN_DI')),

    CONSTRAINT chk_file_dung_luong
        CHECK (dung_luong IS NULL OR dung_luong >= 0)
);

-- =====================================================================
-- V. MODULE QUAN LY QUYET DINH
-- Quyet dinh la mot loai van_ban_di.
-- =====================================================================

CREATE TABLE danh_muc_loai_quyet_dinh (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_loai_quyet_dinh      varchar(50) NOT NULL UNIQUE,
    ten_loai_quyet_dinh     varchar(150) NOT NULL,
    mo_ta                   text
);

-- Vai tro nghiep vu trong mot quyet dinh.
-- Bang nay khac voi bang vai_tro cua RBAC.
CREATE TABLE danh_muc_vai_tro_quyet_dinh (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_vai_tro              varchar(50) NOT NULL UNIQUE,
    ten_vai_tro             varchar(150) NOT NULL,
    mo_ta                   text,
    trang_thai              varchar(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT chk_vai_tro_qd_trang_thai
        CHECK (trang_thai IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE quyet_dinh (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    van_ban_di_id           integer NOT NULL UNIQUE,
    loai_quyet_dinh_id      integer NOT NULL,
    ngay_hieu_luc           date,
    trang_thai              varchar(20) NOT NULL DEFAULT 'DRAFT',
    nguoi_tao_id            integer NOT NULL,
    nguoi_duyet_id          integer,
    ngay_trinh_duyet        timestamp without time zone,
    ngay_duyet              timestamp without time zone,
    ly_do_tu_choi           text,
    ngay_tao                timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat           timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_quyet_dinh_van_ban_di
        FOREIGN KEY (van_ban_di_id)
        REFERENCES van_ban_di(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_quyet_dinh_loai
        FOREIGN KEY (loai_quyet_dinh_id)
        REFERENCES danh_muc_loai_quyet_dinh(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_quyet_dinh_nguoi_tao
        FOREIGN KEY (nguoi_tao_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_quyet_dinh_nguoi_duyet
        FOREIGN KEY (nguoi_duyet_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_quyet_dinh_trang_thai
        CHECK (
            trang_thai IN (
                'DRAFT',
                'SUBMITTED',
                'APPROVED',
                'REJECTED',
                'ISSUED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_quyet_dinh_ngay_duyet
        CHECK (
            ngay_duyet IS NULL
            OR ngay_trinh_duyet IS NULL
            OR ngay_duyet >= ngay_trinh_duyet
        )
);

-- Mot quyet dinh co the co nhieu nguoi/don vi lien quan.
-- Cac cot ho_ten, ten_don_vi va chuc_vu la du lieu snapshot tai thoi diem
-- lap quyet dinh, giup quyet dinh cu khong bi thay doi khi thong tin can bo
-- duoc cap nhat sau nay.
CREATE TABLE thanh_phan_quyet_dinh (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quyet_dinh_id               integer NOT NULL,

    -- Co the chon can bo da co trong he thong
    can_bo_id                   integer,

    -- Thong tin snapshot tren quyet dinh
    ho_ten                      varchar(100) NOT NULL,
    don_vi_id                   integer,
    ten_don_vi                  varchar(255),
    chuc_vu                     varchar(100),

    vai_tro_quyet_dinh_id       integer NOT NULL,
    noi_dung_lien_quan          text,
    thu_tu                      integer NOT NULL DEFAULT 1,
    ghi_chu                     text,

    CONSTRAINT fk_thanh_phan_quyet_dinh
        FOREIGN KEY (quyet_dinh_id)
        REFERENCES quyet_dinh(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_thanh_phan_can_bo
        FOREIGN KEY (can_bo_id)
        REFERENCES can_bo(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_thanh_phan_don_vi
        FOREIGN KEY (don_vi_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_thanh_phan_vai_tro
        FOREIGN KEY (vai_tro_quyet_dinh_id)
        REFERENCES danh_muc_vai_tro_quyet_dinh(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_thanh_phan_thu_tu
        CHECK (thu_tu > 0)
);

CREATE TABLE lich_su_quyet_dinh (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quyet_dinh_id           integer NOT NULL,
    trang_thai_cu           varchar(20),
    trang_thai_moi          varchar(20) NOT NULL,
    hanh_dong               varchar(50) NOT NULL,
    noi_dung_y_kien         text,
    nguoi_thuc_hien_id      integer,
    thoi_gian               timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_lich_su_quyet_dinh
        FOREIGN KEY (quyet_dinh_id)
        REFERENCES quyet_dinh(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_lich_su_qd_nguoi_thuc_hien
        FOREIGN KEY (nguoi_thuc_hien_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- =====================================================================
-- VI. INDEX
-- =====================================================================

CREATE INDEX idx_can_bo_co_quan
    ON can_bo(co_quan_id);

CREATE INDEX idx_tai_khoan_can_bo
    ON tai_khoan(can_bo_id);

CREATE INDEX idx_phong_toa_nha
    ON phong_luu_tru(toa_nha_id);

CREATE INDEX idx_ke_tu_phong
    ON ke_tu_luu_tru(phong_id);

CREATE INDEX idx_ngan_ke_tu
    ON ngan_luu_tru(ke_tu_id);

CREATE INDEX idx_hop_ngan
    ON hop_luu_tru(ngan_id);

CREATE INDEX idx_ho_so_hop
    ON ho_so(hop_luu_tru_id);

CREATE INDEX idx_van_ban_den_co_quan
    ON van_ban_den(co_quan_ban_hanh_id);

CREATE INDEX idx_van_ban_den_loai
    ON van_ban_den(ma_loai_vb_id);

CREATE INDEX idx_van_ban_den_ho_so
    ON van_ban_den(ma_ho_so);

CREATE INDEX idx_van_ban_den_nguoi_xu_ly
    ON van_ban_den(nguoi_xu_ly_id);

CREATE INDEX idx_van_ban_den_nguoi_them_ho_so
    ON van_ban_den(nguoi_them_ho_so_id);

CREATE INDEX idx_van_ban_di_don_vi
    ON van_ban_di(don_vi_soan_thao_id);

CREATE INDEX idx_van_ban_di_loai
    ON van_ban_di(ma_loai_vb_id);

CREATE INDEX idx_van_ban_di_nguoi_ky
    ON van_ban_di(nguoi_ky_id);

CREATE INDEX idx_van_ban_di_ho_so
    ON van_ban_di(ma_ho_so);

CREATE INDEX idx_van_ban_di_nguoi_them_ho_so
    ON van_ban_di(nguoi_them_ho_so_id);

CREATE INDEX idx_file_dinh_kem_van_ban
    ON file_dinh_kem(loai_van_ban, van_ban_id);

CREATE INDEX idx_quyen_module
    ON quyen(module);

CREATE INDEX idx_quyet_dinh_trang_thai
    ON quyet_dinh(trang_thai);

CREATE INDEX idx_quyet_dinh_loai
    ON quyet_dinh(loai_quyet_dinh_id);

CREATE INDEX idx_thanh_phan_quyet_dinh
    ON thanh_phan_quyet_dinh(quyet_dinh_id);

CREATE INDEX idx_thanh_phan_can_bo
    ON thanh_phan_quyet_dinh(can_bo_id);

CREATE INDEX idx_thanh_phan_don_vi
    ON thanh_phan_quyet_dinh(don_vi_id);

CREATE INDEX idx_thanh_phan_vai_tro
    ON thanh_phan_quyet_dinh(vai_tro_quyet_dinh_id);

CREATE INDEX idx_lich_su_quyet_dinh
    ON lich_su_quyet_dinh(quyet_dinh_id, thoi_gian);

-- =====================================================================
-- VII. TRIGGER CAP NHAT ngay_cap_nhat
-- =====================================================================

CREATE OR REPLACE FUNCTION fn_cap_nhat_thoi_gian()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.ngay_cap_nhat := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_tai_khoan_cap_nhat
BEFORE UPDATE ON tai_khoan
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_thoi_gian();

CREATE TRIGGER trg_quyet_dinh_cap_nhat
BEFORE UPDATE ON quyet_dinh
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_thoi_gian();

-- =====================================================================
-- VIII. DU LIEU MAU TOI THIEU
-- =====================================================================

INSERT INTO vai_tro (ma_vai_tro, ten_vai_tro, mo_ta)
VALUES
    ('ADMIN', 'Quan tri he thong', 'Quan ly tai khoan, vai tro va quyen'),
    ('VAN_THU', 'Van thu', 'Quan ly van ban, ho so va lap quyet dinh'),
    ('LANH_DAO', 'Lanh dao', 'Phe duyet va ban hanh quyet dinh'),
    ('TRA_CUU', 'Tra cuu', 'Chi duoc xem du lieu');

INSERT INTO quyen (ma_quyen, ten_quyen, module, hanh_dong)
VALUES
    ('TAI_KHOAN.MANAGE', 'Quan ly tai khoan', 'TAI_KHOAN', 'MANAGE'),
    ('PHAN_QUYEN.MANAGE', 'Quan ly vai tro va quyen', 'PHAN_QUYEN', 'MANAGE'),

    ('VI_TRI_LUU_TRU.VIEW', 'Xem vi tri luu tru', 'VI_TRI_LUU_TRU', 'VIEW'),
    ('VI_TRI_LUU_TRU.MANAGE', 'Quan ly vi tri luu tru', 'VI_TRI_LUU_TRU', 'MANAGE'),

    ('HO_SO.VIEW', 'Xem ho so', 'HO_SO', 'VIEW'),
    ('HO_SO.CREATE', 'Tao ho so', 'HO_SO', 'CREATE'),
    ('HO_SO.UPDATE', 'Cap nhat ho so', 'HO_SO', 'UPDATE'),
    ('HO_SO.ADD_DOCUMENT', 'Them van ban vao ho so', 'HO_SO', 'ADD_DOCUMENT'),

    ('VAN_BAN_DEN.VIEW', 'Xem van ban den', 'VAN_BAN_DEN', 'VIEW'),
    ('VAN_BAN_DEN.CREATE', 'Tao van ban den', 'VAN_BAN_DEN', 'CREATE'),
    ('VAN_BAN_DEN.UPDATE', 'Cap nhat van ban den', 'VAN_BAN_DEN', 'UPDATE'),

    ('VAN_BAN_DI.VIEW', 'Xem van ban di', 'VAN_BAN_DI', 'VIEW'),
    ('VAN_BAN_DI.CREATE', 'Tao van ban di', 'VAN_BAN_DI', 'CREATE'),
    ('VAN_BAN_DI.UPDATE', 'Cap nhat van ban di', 'VAN_BAN_DI', 'UPDATE'),

    ('QUYET_DINH.VIEW', 'Xem quyet dinh', 'QUYET_DINH', 'VIEW'),
    ('QUYET_DINH.CREATE', 'Tao quyet dinh', 'QUYET_DINH', 'CREATE'),
    ('QUYET_DINH.UPDATE', 'Cap nhat quyet dinh', 'QUYET_DINH', 'UPDATE'),
    ('QUYET_DINH.SUBMIT', 'Trinh duyet quyet dinh', 'QUYET_DINH', 'SUBMIT'),
    ('QUYET_DINH.APPROVE', 'Phe duyet quyet dinh', 'QUYET_DINH', 'APPROVE'),
    ('QUYET_DINH.REJECT', 'Tu choi quyet dinh', 'QUYET_DINH', 'REJECT'),
    ('QUYET_DINH.ISSUE', 'Ban hanh quyet dinh', 'QUYET_DINH', 'ISSUE');

-- ADMIN: tat ca quyen.
INSERT INTO vai_tro_quyen (vai_tro_id, quyen_id)
SELECT vt.id, q.id
FROM vai_tro vt
CROSS JOIN quyen q
WHERE vt.ma_vai_tro = 'ADMIN';

-- VAN_THU: quan ly vi tri, ho so, van ban va tao/trinh quyet dinh.
INSERT INTO vai_tro_quyen (vai_tro_id, quyen_id)
SELECT vt.id, q.id
FROM vai_tro vt
JOIN quyen q
  ON q.ma_quyen IN (
      'VI_TRI_LUU_TRU.VIEW',
      'VI_TRI_LUU_TRU.MANAGE',
      'HO_SO.VIEW',
      'HO_SO.CREATE',
      'HO_SO.UPDATE',
      'HO_SO.ADD_DOCUMENT',
      'VAN_BAN_DEN.VIEW',
      'VAN_BAN_DEN.CREATE',
      'VAN_BAN_DEN.UPDATE',
      'VAN_BAN_DI.VIEW',
      'VAN_BAN_DI.CREATE',
      'VAN_BAN_DI.UPDATE',
      'QUYET_DINH.VIEW',
      'QUYET_DINH.CREATE',
      'QUYET_DINH.UPDATE',
      'QUYET_DINH.SUBMIT'
  )
WHERE vt.ma_vai_tro = 'VAN_THU';

-- LANH_DAO: xem ho so, van ban; phe duyet, tu choi va ban hanh.
INSERT INTO vai_tro_quyen (vai_tro_id, quyen_id)
SELECT vt.id, q.id
FROM vai_tro vt
JOIN quyen q
  ON q.ma_quyen IN (
      'VI_TRI_LUU_TRU.VIEW',
      'HO_SO.VIEW',
      'VAN_BAN_DEN.VIEW',
      'VAN_BAN_DI.VIEW',
      'QUYET_DINH.VIEW',
      'QUYET_DINH.APPROVE',
      'QUYET_DINH.REJECT',
      'QUYET_DINH.ISSUE'
  )
WHERE vt.ma_vai_tro = 'LANH_DAO';

-- TRA_CUU: chi xem.
INSERT INTO vai_tro_quyen (vai_tro_id, quyen_id)
SELECT vt.id, q.id
FROM vai_tro vt
JOIN quyen q
  ON q.ma_quyen IN (
      'VI_TRI_LUU_TRU.VIEW',
      'HO_SO.VIEW',
      'VAN_BAN_DEN.VIEW',
      'VAN_BAN_DI.VIEW',
      'QUYET_DINH.VIEW'
  )
WHERE vt.ma_vai_tro = 'TRA_CUU';

INSERT INTO danh_muc_loai_quyet_dinh
    (ma_loai_quyet_dinh, ten_loai_quyet_dinh, mo_ta)
VALUES
    ('BO_NHIEM', 'Quyet dinh bo nhiem', NULL),
    ('KHEN_THUONG', 'Quyet dinh khen thuong', NULL),
    ('KY_LUAT', 'Quyet dinh ky luat', NULL),
    ('DIEU_DONG', 'Quyet dinh dieu dong', NULL),
    ('KHAC', 'Quyet dinh khac', NULL);

INSERT INTO danh_muc_vai_tro_quyet_dinh
    (ma_vai_tro, ten_vai_tro, mo_ta)
VALUES
    ('DOI_TUONG', 'Doi tuong cua quyet dinh', NULL),
    ('NGUOI_DUOC_BO_NHIEM', 'Nguoi duoc bo nhiem', NULL),
    ('NGUOI_DUOC_DIEU_DONG', 'Nguoi duoc dieu dong', NULL),
    ('DAI_DIEN_DON_VI', 'Dai dien don vi', NULL),
    ('NGUOI_KY', 'Nguoi ky quyet dinh', NULL),
    ('NGUOI_PHOI_HOP', 'Nguoi phoi hop thuc hien', NULL),
    ('KHAC', 'Vai tro khac', NULL);

COMMIT;

-- =====================================================================
-- KET QUA
--   Tong cong: 23 bang
--
--   Nhom danh muc/to chuc:               3 bang
--   Nhom RBAC:                           5 bang
--   Nhom vi tri luu tru:                 5 bang
--   Nhom ho so va van ban:               5 bang
--   Nhom quyet dinh:                     5 bang
--
-- Quan he chinh:
--   toa_nha 1-N phong_luu_tru
--   phong_luu_tru 1-N ke_tu_luu_tru
--   ke_tu_luu_tru 1-N ngan_luu_tru
--   ngan_luu_tru 1-N hop_luu_tru
--   hop_luu_tru 1-N ho_so
--   ho_so 1-N van_ban_den
--   ho_so 1-N van_ban_di
--   van_ban_di 1-0..1 quyet_dinh
--   quyet_dinh 1-N thanh_phan_quyet_dinh
-- =====================================================================
