-- =====================================================================
-- QLVB - PostgreSQL
-- Pham vi:
--   1. Giu nguyen cac bang trong ERD ban dau.
--   2. Chi bo sung phan quyen RBAC.
--   3. Chi bo sung module quan ly quyet dinh.
--
-- LUU Y:
--   File nay tao lai schema public tu dau.
--   Chi chay khi database chua co du lieu quan trong.
-- =====================================================================

BEGIN;

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO public;

SET search_path TO public;

-- =====================================================================
-- I. CAC BANG GOC TU ERD BAN DAU
-- =====================================================================

CREATE TABLE danh_muc_loai_vb (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_loai_vb     varchar(100) NOT NULL UNIQUE,
    mo_ta           text
);

CREATE TABLE co_quan_to_chuc (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_co_quan     varchar(255) NOT NULL,
    organ_id        varchar(13) NOT NULL UNIQUE,
    dia_chi         varchar(500)
);

CREATE TABLE can_bo (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten          varchar(100) NOT NULL,
    chuc_vu         varchar(100),
    co_quan_id      integer NOT NULL,

    CONSTRAINT fk_can_bo_co_quan
        FOREIGN KEY (co_quan_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE vi_tri_luu_tru (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    toa_nha         varchar(255),
    phong           varchar(100),
    ke_tu           varchar(100),
    ngan_tang       varchar(100),
    so_hop          varchar(100),
    ghi_chu         text
);

CREATE TABLE ho_so (
    ma_ho_so            varchar(50) PRIMARY KEY,
    tieu_de_ho_so       varchar(500) NOT NULL,
    thoi_han_bao_quan   varchar(50),
    che_do_su_dung      varchar(50),
    ngay_bat_dau        date,
    ngay_ket_thuc       date,
    so_luong_trang      integer DEFAULT 0,
    so_luong_van_ban    integer DEFAULT 0,
    nguoi_lap           varchar(100),
    ngon_ngu            varchar(50),
    ghi_chu             text,
    vi_tri_id           integer,

    CONSTRAINT fk_ho_so_vi_tri
        FOREIGN KEY (vi_tri_id)
        REFERENCES vi_tri_luu_tru(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_ho_so_ngay
        CHECK (
            ngay_ket_thuc IS NULL
            OR ngay_bat_dau IS NULL
            OR ngay_ket_thuc >= ngay_bat_dau
        ),

    CONSTRAINT chk_ho_so_so_luong_trang
        CHECK (so_luong_trang IS NULL OR so_luong_trang >= 0),

    CONSTRAINT chk_ho_so_so_luong_van_ban
        CHECK (so_luong_van_ban IS NULL OR so_luong_van_ban >= 0)
);

CREATE TABLE van_ban_den (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_den                  integer NOT NULL,
    ky_hieu                 varchar(100),
    ngay_den                date NOT NULL,
    ngay_ban_hanh           date,
    co_quan_ban_hanh_id     integer,
    ma_loai_vb_id           integer NOT NULL,
    trich_yeu               text NOT NULL,
    ngon_ngu                varchar(30),
    so_trang                integer,
    ho_ten_nguoi_ky         varchar(50),
    chuc_vu_nguoi_ky        varchar(100),
    linh_vuc                text,
    do_khan                 integer,
    don_vi_nhan             text,
    han_giai_quyet          date,
    y_kien_chi_dao          text,
    stt_trong_ho_so         integer,
    ma_ho_so                varchar(50),

    CONSTRAINT fk_van_ban_den_co_quan
        FOREIGN KEY (co_quan_ban_hanh_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_van_ban_den_loai_vb
        FOREIGN KEY (ma_loai_vb_id)
        REFERENCES danh_muc_loai_vb(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_van_ban_den_ho_so
        FOREIGN KEY (ma_ho_so)
        REFERENCES ho_so(ma_ho_so)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_van_ban_den_so_den
        CHECK (so_den > 0),

    CONSTRAINT chk_van_ban_den_so_trang
        CHECK (so_trang IS NULL OR so_trang >= 0),

    CONSTRAINT chk_van_ban_den_do_khan
        CHECK (do_khan IS NULL OR do_khan BETWEEN 1 AND 5)
);

CREATE TABLE van_ban_di (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_ky_hieu              varchar(50),
    ngay_ban_hanh           date,
    trich_yeu               text NOT NULL,
    don_vi_soan_thao_id     integer NOT NULL,
    ma_loai_vb_id           integer NOT NULL,
    ngon_ngu                varchar(30),
    so_trang                integer,
    ghi_chu                 text,
    nguoi_ky_id             integer,
    chuc_vu_nguoi_ky        varchar(100),
    noi_nhan                varchar(100),
    muc_do_khan             integer,
    han_tra_loi             date,
    stt_trong_ho_so         integer,
    ma_ho_so                varchar(50),

    CONSTRAINT fk_van_ban_di_don_vi_soan_thao
        FOREIGN KEY (don_vi_soan_thao_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_van_ban_di_loai_vb
        FOREIGN KEY (ma_loai_vb_id)
        REFERENCES danh_muc_loai_vb(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_van_ban_di_nguoi_ky
        FOREIGN KEY (nguoi_ky_id)
        REFERENCES can_bo(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_van_ban_di_ho_so
        FOREIGN KEY (ma_ho_so)
        REFERENCES ho_so(ma_ho_so)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_van_ban_di_so_trang
        CHECK (so_trang IS NULL OR so_trang >= 0),

    CONSTRAINT chk_van_ban_di_muc_do_khan
        CHECK (muc_do_khan IS NULL OR muc_do_khan BETWEEN 1 AND 5)
);

CREATE TABLE noi_nhan_van_ban (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    van_ban_di_id           integer NOT NULL,
    co_quan_nhan_id         integer NOT NULL,
    phuong_thuc_gui         varchar(100),

    CONSTRAINT fk_noi_nhan_van_ban_di
        FOREIGN KEY (van_ban_di_id)
        REFERENCES van_ban_di(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_noi_nhan_co_quan
        FOREIGN KEY (co_quan_nhan_id)
        REFERENCES co_quan_to_chuc(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uk_noi_nhan_van_ban
        UNIQUE (van_ban_di_id, co_quan_nhan_id)
);

CREATE TABLE file_dinh_kem (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loai_van_ban    varchar(20) NOT NULL,
    van_ban_id      integer NOT NULL,
    ten_file        varchar(255) NOT NULL,
    duong_dan       varchar(500) NOT NULL,
    dinh_dang       varchar(10),
    dung_luong      double precision,
    ngay_tao        timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_file_loai_van_ban
        CHECK (loai_van_ban IN ('VAN_BAN_DEN', 'VAN_BAN_DI')),

    CONSTRAINT chk_file_dung_luong
        CHECK (dung_luong IS NULL OR dung_luong >= 0)
);

-- =====================================================================
-- II. PHAN QUYEN RBAC - BO SUNG VUA DU
-- =====================================================================

CREATE TABLE tai_khoan (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id           integer UNIQUE,
    ten_dang_nhap       varchar(100) NOT NULL UNIQUE,
    mat_khau_hash       varchar(255) NOT NULL,
    trang_thai          varchar(20) NOT NULL DEFAULT 'ACTIVE',
    ngay_tao            timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat       timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tai_khoan_can_bo
        FOREIGN KEY (can_bo_id)
        REFERENCES can_bo(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_tai_khoan_trang_thai
        CHECK (trang_thai IN ('ACTIVE', 'LOCKED', 'INACTIVE'))
);

CREATE TABLE vai_tro (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_vai_tro      varchar(50) NOT NULL UNIQUE,
    ten_vai_tro     varchar(100) NOT NULL,
    mo_ta           varchar(500)
);

CREATE TABLE quyen (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_quyen        varchar(100) NOT NULL UNIQUE,
    ten_quyen       varchar(150) NOT NULL,
    module          varchar(50) NOT NULL,
    hanh_dong       varchar(30) NOT NULL
);

CREATE TABLE tai_khoan_vai_tro (
    tai_khoan_id    integer NOT NULL,
    vai_tro_id      integer NOT NULL,

    PRIMARY KEY (tai_khoan_id, vai_tro_id),

    CONSTRAINT fk_tkvt_tai_khoan
        FOREIGN KEY (tai_khoan_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_tkvt_vai_tro
        FOREIGN KEY (vai_tro_id)
        REFERENCES vai_tro(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE vai_tro_quyen (
    vai_tro_id      integer NOT NULL,
    quyen_id        integer NOT NULL,

    PRIMARY KEY (vai_tro_id, quyen_id),

    CONSTRAINT fk_vtq_vai_tro
        FOREIGN KEY (vai_tro_id)
        REFERENCES vai_tro(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_vtq_quyen
        FOREIGN KEY (quyen_id)
        REFERENCES quyen(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- =====================================================================
-- III. MODULE QUAN LY QUYET DINH - BO SUNG VUA DU
-- Quyet dinh la mot loai VAN_BAN_DI, bang quyet_dinh chi luu nghiep vu rieng.
-- =====================================================================

CREATE TABLE danh_muc_loai_quyet_dinh (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_loai_quyet_dinh      varchar(50) NOT NULL UNIQUE,
    ten_loai_quyet_dinh     varchar(150) NOT NULL,
    mo_ta                   text
);

CREATE TABLE quyet_dinh (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    van_ban_di_id           integer NOT NULL UNIQUE,
    loai_quyet_dinh_id      integer NOT NULL,
    ngay_hieu_luc           date,
    trang_thai              varchar(20) NOT NULL DEFAULT 'DRAFT',
    nguoi_tao_id            integer NOT NULL,
    nguoi_duyet_id          integer,
    ngay_trinh_duyet        timestamp without time zone,
    ngay_duyet              timestamp without time zone,
    ly_do_tu_choi           text,
    ngay_tao                timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat           timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_quyet_dinh_van_ban_di
        FOREIGN KEY (van_ban_di_id)
        REFERENCES van_ban_di(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_quyet_dinh_loai
        FOREIGN KEY (loai_quyet_dinh_id)
        REFERENCES danh_muc_loai_quyet_dinh(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_quyet_dinh_nguoi_tao
        FOREIGN KEY (nguoi_tao_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_quyet_dinh_nguoi_duyet
        FOREIGN KEY (nguoi_duyet_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_quyet_dinh_trang_thai
        CHECK (
            trang_thai IN (
                'DRAFT',
                'SUBMITTED',
                'APPROVED',
                'REJECTED',
                'ISSUED',
                'CANCELLED'
            )
        )
);

CREATE TABLE lich_su_quyet_dinh (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quyet_dinh_id           integer NOT NULL,
    trang_thai_cu           varchar(20),
    trang_thai_moi          varchar(20) NOT NULL,
    hanh_dong               varchar(50) NOT NULL,
    noi_dung_y_kien         text,
    nguoi_thuc_hien_id      integer,
    thoi_gian               timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_lich_su_quyet_dinh
        FOREIGN KEY (quyet_dinh_id)
        REFERENCES quyet_dinh(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_lich_su_qd_nguoi_thuc_hien
        FOREIGN KEY (nguoi_thuc_hien_id)
        REFERENCES tai_khoan(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- =====================================================================
-- IV. INDEX
-- =====================================================================

CREATE INDEX idx_can_bo_co_quan
    ON can_bo(co_quan_id);

CREATE INDEX idx_ho_so_vi_tri
    ON ho_so(vi_tri_id);

CREATE INDEX idx_van_ban_den_co_quan
    ON van_ban_den(co_quan_ban_hanh_id);

CREATE INDEX idx_van_ban_den_loai
    ON van_ban_den(ma_loai_vb_id);

CREATE INDEX idx_van_ban_den_ho_so
    ON van_ban_den(ma_ho_so);

CREATE INDEX idx_van_ban_di_don_vi
    ON van_ban_di(don_vi_soan_thao_id);

CREATE INDEX idx_van_ban_di_loai
    ON van_ban_di(ma_loai_vb_id);

CREATE INDEX idx_van_ban_di_nguoi_ky
    ON van_ban_di(nguoi_ky_id);

CREATE INDEX idx_van_ban_di_ho_so
    ON van_ban_di(ma_ho_so);

CREATE INDEX idx_file_dinh_kem_van_ban
    ON file_dinh_kem(loai_van_ban, van_ban_id);

CREATE INDEX idx_quyen_module
    ON quyen(module);

CREATE INDEX idx_quyet_dinh_trang_thai
    ON quyet_dinh(trang_thai);

CREATE INDEX idx_quyet_dinh_loai
    ON quyet_dinh(loai_quyet_dinh_id);

CREATE INDEX idx_lich_su_quyet_dinh
    ON lich_su_quyet_dinh(quyet_dinh_id, thoi_gian);

-- =====================================================================
-- V. TRIGGER CAP NHAT ngay_cap_nhat
-- =====================================================================

CREATE OR REPLACE FUNCTION fn_cap_nhat_thoi_gian()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.ngay_cap_nhat := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_tai_khoan_cap_nhat
BEFORE UPDATE ON tai_khoan
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_thoi_gian();

CREATE TRIGGER trg_quyet_dinh_cap_nhat
BEFORE UPDATE ON quyet_dinh
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_thoi_gian();

-- =====================================================================
-- VI. DU LIEU MAU TOI THIEU CHO PHAN QUYEN VA QUYET DINH
-- =====================================================================

INSERT INTO vai_tro (ma_vai_tro, ten_vai_tro, mo_ta)
VALUES
    ('ADMIN', 'Quan tri he thong', 'Quan ly tai khoan, vai tro va quyen'),
    ('VAN_THU', 'Van thu', 'Quan ly van ban va lap quyet dinh'),
    ('LANH_DAO', 'Lanh dao', 'Phe duyet va ban hanh quyet dinh'),
    ('TRA_CUU', 'Tra cuu', 'Chi duoc xem du lieu');

INSERT INTO quyen (ma_quyen, ten_quyen, module, hanh_dong)
VALUES
    ('TAI_KHOAN.MANAGE', 'Quan ly tai khoan', 'TAI_KHOAN', 'MANAGE'),
    ('PHAN_QUYEN.MANAGE', 'Quan ly vai tro va quyen', 'PHAN_QUYEN', 'MANAGE'),

    ('VAN_BAN_DEN.VIEW', 'Xem van ban den', 'VAN_BAN_DEN', 'VIEW'),
    ('VAN_BAN_DEN.CREATE', 'Tao van ban den', 'VAN_BAN_DEN', 'CREATE'),
    ('VAN_BAN_DEN.UPDATE', 'Cap nhat van ban den', 'VAN_BAN_DEN', 'UPDATE'),

    ('VAN_BAN_DI.VIEW', 'Xem van ban di', 'VAN_BAN_DI', 'VIEW'),
    ('VAN_BAN_DI.CREATE', 'Tao van ban di', 'VAN_BAN_DI', 'CREATE'),
    ('VAN_BAN_DI.UPDATE', 'Cap nhat van ban di', 'VAN_BAN_DI', 'UPDATE'),

    ('QUYET_DINH.VIEW', 'Xem quyet dinh', 'QUYET_DINH', 'VIEW'),
    ('QUYET_DINH.CREATE', 'Tao quyet dinh', 'QUYET_DINH', 'CREATE'),
    ('QUYET_DINH.UPDATE', 'Cap nhat quyet dinh', 'QUYET_DINH', 'UPDATE'),
    ('QUYET_DINH.SUBMIT', 'Trinh duyet quyet dinh', 'QUYET_DINH', 'SUBMIT'),
    ('QUYET_DINH.APPROVE', 'Phe duyet quyet dinh', 'QUYET_DINH', 'APPROVE'),
    ('QUYET_DINH.REJECT', 'Tu choi quyet dinh', 'QUYET_DINH', 'REJECT'),
    ('QUYET_DINH.ISSUE', 'Ban hanh quyet dinh', 'QUYET_DINH', 'ISSUE');

-- ADMIN: tat ca quyen.
INSERT INTO vai_tro_quyen (vai_tro_id, quyen_id)
SELECT vt.id, q.id
FROM vai_tro vt
CROSS JOIN quyen q
WHERE vt.ma_vai_tro = 'ADMIN';

-- VAN_THU: van ban va tao/trinh quyet dinh.
INSERT INTO vai_tro_quyen (vai_tro_id, quyen_id)
SELECT vt.id, q.id
FROM vai_tro vt
JOIN quyen q
  ON q.ma_quyen IN (
      'VAN_BAN_DEN.VIEW',
      'VAN_BAN_DEN.CREATE',
      'VAN_BAN_DEN.UPDATE',
      'VAN_BAN_DI.VIEW',
      'VAN_BAN_DI.CREATE',
      'VAN_BAN_DI.UPDATE',
      'QUYET_DINH.VIEW',
      'QUYET_DINH.CREATE',
      'QUYET_DINH.UPDATE',
      'QUYET_DINH.SUBMIT'
  )
WHERE vt.ma_vai_tro = 'VAN_THU';

-- LANH_DAO: xem, phe duyet, tu choi va ban hanh.
INSERT INTO vai_tro_quyen (vai_tro_id, quyen_id)
SELECT vt.id, q.id
FROM vai_tro vt
JOIN quyen q
  ON q.ma_quyen IN (
      'VAN_BAN_DEN.VIEW',
      'VAN_BAN_DI.VIEW',
      'QUYET_DINH.VIEW',
      'QUYET_DINH.APPROVE',
      'QUYET_DINH.REJECT',
      'QUYET_DINH.ISSUE'
  )
WHERE vt.ma_vai_tro = 'LANH_DAO';

-- TRA_CUU: chi xem.
INSERT INTO vai_tro_quyen (vai_tro_id, quyen_id)
SELECT vt.id, q.id
FROM vai_tro vt
JOIN quyen q
  ON q.ma_quyen IN (
      'VAN_BAN_DEN.VIEW',
      'VAN_BAN_DI.VIEW',
      'QUYET_DINH.VIEW'
  )
WHERE vt.ma_vai_tro = 'TRA_CUU';

INSERT INTO danh_muc_loai_quyet_dinh
    (ma_loai_quyet_dinh, ten_loai_quyet_dinh, mo_ta)
VALUES
    ('BO_NHIEM', 'Quyet dinh bo nhiem', NULL),
    ('KHEN_THUONG', 'Quyet dinh khen thuong', NULL),
    ('KY_LUAT', 'Quyet dinh ky luat', NULL),
    ('DIEU_DONG', 'Quyet dinh dieu dong', NULL),
    ('KHAC', 'Quyet dinh khac', NULL);

ALTER TABLE van_ban_di ADD COLUMN so_luong_ban_phat_hanh INTEGER;
ALTER TABLE ho_so ADD COLUMN file_catalog INTEGER;
ALTER TABLE ho_so ADD COLUMN file_notation VARCHAR(50);
ALTER TABLE ho_so ADD COLUMN trang_thai VARCHAR(50) DEFAULT 'DANG_MO';
ALTER TABLE van_ban_den ADD COLUMN trang_thai_xu_ly VARCHAR(50) DEFAULT 'CHO_XU_LY';
ALTER TABLE van_ban_di ADD COLUMN trang_thai VARCHAR(50) DEFAULT 'DRAFT';
ALTER TABLE van_ban_den ADD COLUMN nguoi_xu_ly_id INTEGER REFERENCES can_bo(id) ON DELETE SET NULL;

-- ALTER TABLE van_ban_di ADD COLUMN submitted_at TIMESTAMP WITHOUT TIME ZONE;
-- ALTER TABLE van_ban_di ADD COLUMN approved_by VARCHAR(100);
-- ALTER TABLE van_ban_di ADD COLUMN approved_at TIMESTAMP WITHOUT TIME ZONE;
-- ALTER TABLE van_ban_di ADD COLUMN revoke_reason TEXT;

COMMIT;

-- =====================================================================
-- KET QUA:
--   8 bang goc
--   5 bang phan quyen
--   3 bang quyet dinh
--   Tong cong: 16 bang
-- =====================================================================
